controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

index:
  path: /
  methods: [ "GET" ]
  controller: App\Controller\DefaultController::index

locations:
  path: /locations
  methods: [ "GET" ]
  controller: App\Controller\LocationController::index

locations_update:
  path: /locations/update/
  methods: [ "GET", "POST" ]
  controller: App\Controller\LocationController::edit

app_locataire_index:
  path: /locataire/
  methods: [ "GET" ]
  controller: App\Controller\LocataireController::index

app_locataire_new:
  path: /locataire/{id}/new
  methods: [ "GET", "POST" ]
  controller: App\Controller\LocataireController::new
  requirements:
    id: '\d+'

app_locataire_show:
  path: /locataire/{id}
  methods: [ "GET" ]
  controller: App\Controller\LocataireController::show
  requirements:
    id: '\d+'

app_locataire_edit:
  path: /locataire/{id}/edit
  methods: [ "GET", "POST" ]
  controller: App\Controller\LocataireController::edit
  requirements:
    id: '\d+'

app_locataire_delete:
  path: /locataire/{id}
  methods: [ "POST" ]
  controller: App\Controller\LocataireController::delete
  requirements:
    id: '\d+'

app_location_index:
  path: /location/
  methods: [ "GET" ]
  controller: App\Controller\LocationController::index

app_location_show:
  path: /location/{id}
  methods: [ "GET" ]
  controller: App\Controller\LocationController::show
  requirements:
    id: '\d+'

app_location_edit:
  path: /location/{id}/edit
  methods: [ "GET", "POST" ]
  controller: App\Controller\LocationController::edit
  requirements:
    id: '\d+'

app_location_delete:
  path: /location/{id}
  methods: [ "POST" ]
  controller: App\Controller\LocationController::delete
  requirements:
    id: '\d+'

app_mandataire_index:
  path: /mandataire/
  methods: [ "GET" ]
  controller: App\Controller\MandataireController::index

app_mandataire_edit:
  path: /mandataire/{id}/edit
  methods: [ "GET", "POST" ]
  controller: App\Controller\MandataireController::edit
  requirements:
    id: '\d+'

connexion:
    path: /connexion
    methods: [ "GET", "POST" ]
    controller: App\Controller\ConnexionController::index

connexion_home:
    path: /connexion/home/{id}
    methods: [ "GET", "POST" ]
    controller: App\Controller\ConnexionController::home